export default StorageNames = {
  USER_PROFILE: "USER_PROFILE",
  LOCATION_TIME: "LOCATION_TIME",
  ADDRESS_SEARCH: "ADDRESS_SEARCH",
  MENU_SERVICE: "MENU_SERVICE",
  ORDER_SERVICE: "ORDER_SERVICE",
  SERVICE_CONFIRM: "SERVICE_CONFIRM",
  SERVICE_PENDING: "SERVICE_PENDING",
  BENEFIT_VALUE: "BENEFIT_VALUE",
};
