const mainTypes = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  CallServer: "CallServer",
  LOCATION_TIME: "LOCATION_TIME",
  USER_PROFILE: "USER_PROFILE",
  MENU_SERVICE: "MENU_SERVICE",
  CHECK_PERMISSION: "CHECK_PERMISSION",
  SERVICE_LIST: "SERVICE_LIST",
  MY_ORDER_ACCEPTED: "MY_ORDER_ACCEPTED",
  ACCEPTED_ORDER: "ACCEPTED_ORDER",
  SERVICE_CONFIRM: "SERVICE_CONFIRM",
};
export default mainTypes;
